defaults:
  - _self_
  - hydra: default
  
mode: train

debug: false

general:

  # Dictates whether we allow executions from a 
  # dirty git working tree. If strict, then any
  # uncommitted changes will prevent execution.
  strict_git_clean: false

  # used for lightning's seed_everything function
  global_seed: 10

dataset:
  # This is where datasets will be located or downloaded under.
  # Relative to the current working directory (before any Hydra
  # chdir changes).
  base_dir: datasets
  num_workers: 1

trainer:
  max_epochs: 10

  # how many batches should be seen before accumulating
  # gradients during training. Effectively increases
  # batch size while staying within the available
  # device memory
  grad_acc: 1
